apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  namespace: odilia
  labels:
    app: yelb-appserver
    tier: middletier
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4567
      targetPort: 4567
  selector:
    app: yelb-appserver
    tier: middletier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
  namespace: odilia
  labels:
    app: yelb-appserver
    tier: middletier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelb-appserver
      tier: middletier
  template:
    metadata:
      labels:
        app: yelb-appserver
        tier: middletier
    spec:
      containers:
        - name: yelb-appserver
          image: mreferre/yelb-appserver:0.5
          ports:
            - containerPort: 4567
          readinessProbe:
            tcpSocket:
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4567
            initialDelaySeconds: 30
            periodSeconds: 20

